# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: BuildAndTestSeconds

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Install .NET Maui
      run: dotnet workload install maui
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build Seconds/SecondsClient.csproj -c Release -f net8.0-android --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
